version: '2'
services:
  web:
    image: culturagovbr/salic-web:1.5
    container_name: salic-web
    ports:
     - "80:80"
     - "8888:8888"
    volumes:
     - .:/var/www/salic
     - ./log/apache2:/var/log/apache2
     - ./public/txt:/var/www/salic/public/txt/
     - ./public/plenaria:/var/www/salic/public/plenaria/
    environment:
      - APPLICATION_ENV=development
      #xDebug configs for 'development' enviroment
      - XDEBUG_INSTALL="true"
      - XDEBUG_REMOTE_ENABLE=on
      - XDEBUG_REMOTE_AUTOSTART=on
      - XDEBUG_REMOTE_HANDLER=dbgp
      - XDEBUG_REMOTE_CONNECT_BACK=1
      - XDEBUG_PROFILER_ENABLE=1
      - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini

      - XDEBUG_DEFAULT_ENABLE=1
      - XDEBUG_IDEKEY=PHPSTORM
    networks:
      static-network:
        ipv4_address: 172.20.0.3
networks:
   static-network:
    ipam:
      config:
         - subnet: 172.20.0.0/16
           ip_range: 172.28.5.0/24